# Your project's server will run on localhost:xxxx at this port
PORT: 8080

# Your aws ec2 instance
REMOTE_SERVER:
  production:
    hostname: "ec2-35-154-170-186.ap-south-1.compute.amazonaws.com"
    user: "ec2-user"
    pk_path: "/Users/rahulthakur319//Work/SuppliersCave/dev/archive/keys/rahulsupplierscave.pem"
    directory: "fullstack"
    local_ssh: "www.supplierscave.com"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "src/assets/js/**/*.scss"
    - "src/assets/js/**/*.html"
    - "src/pages/robots.txt"
    - "!src/assets/js/**/*.js"
    - "!src/assets/{img,scss}/**/*"
  # Paths to Css libraries
  # css:
  #   - "src/assets/icons/foundation-icons/foundation-icons.css"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
    - "bower_components/angular-material/angular-material.min.css"
    - "bower_components/angular-ui-grid/ui-grid.min.css"
    - "bower_components/chart.js/dist/Chart.min.css"
    - "bower_components/slick-carousel/slick/slick.css"
    - "bower_components/slick-carousel/slick/slick-theme.css"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    angular: # Essentials - Bare Minimum
      - "bower_components/what-input/dist/what-input.min.js"
      - "bower_components/angular/angular.min.js"
      - "bower_components/angular-aria/angular-aria.min.js"
      - "bower_components/angular-material/angular-material.min.js"
      - "bower_components/oclazyload/dist/ocLazyLoad.min.js"
      - "bower_components/angular-material-data-table/dist/md-data-table.min.js"
      - "bower_components/angular-ui-router/release/angular-ui-router.min.js"
      - "bower_components/angular-messages/angular-messages.min.js" # core angular feature
      - "bower_components/angular-touch/angular-touch.min.js" # requried by mm.foundation
      - "bower_components/angular-animate/angular-animate.min.js" # core angular feature ngAnimate
      - "bower_components/angular-sanitize/angular-sanitize.min.js"
      - "bower_components/angular-wheelie/dist/angular-wheelie.min.js"
      - "bower_components/angular-scrollie/dist/angular-scrollie.min.js"
      - "bower_components/angular-cookies/angular-cookies.min.js"
      - "bower_components/angular-local-storage/dist/angular-local-storage.min.js"
      - "bower_components/angular-ui-grid/ui-grid.min.js"
      - "src/assets/js/app.js"
      - "src/assets/js/**/*.routes.js"
      - "src/assets/js/routes/**/*.js"
      - "src/assets/js/app.config.js"
      - "src/assets/js/app.controller.js"
    bower: # Bower based optional - to be loaded as per the requirements
      # Angular Foundation Directive
      - "bower_components/angular-foundation-6/dist/angular-foundation.min.js" # mm.foundation
      - "bower_components/ngprogress/build/ngprogress.min.js"
      - "bower_components/angular-filter/dist/angular-filter.min.js"
      - "bower_components/angular-snapscroll/dist/angular-snapscroll.min.js"
      
      # Angular Touch Support 
      - "bower_components/hammerjs/hammer.min.js"
      - "bower_components/AngularHammer/angular.hammer.min.js"
      # Angular Material
      - "bower_components/angular-material/angular-material.min.js"
      # Extras
      - "bower_components/angular-ui-notification/dist/angular-ui-notification.min.js"
      - "bower_components/angucomplete-alt/dist/angucomplete-alt.min.js"
      - "bower_components/aws-sdk/dist/aws-sdk.min.js"
      - "bower_components/ng-lodash/build/ng-lodash.min.js"
      # Angular Chart
      - "bower_components/chart.js/dist/Chart.min.js"
      - "bower_components/angular-chart.js/dist/angular-chart.min.js"
      #jquery
      - "bower_components/jquery/dist/jquery.min.js"
      #slick-carousel
      - "bower_components/slick-carousel/slick/slick.min.js"
      #angular-slick-carousel
      - "bower_components/angular-slick-carousel/dist/angular-slick.min.js"
      
    app:
      - "src/assets/js/controllers/**/*.js"
      - "src/assets/js/services/**/*.js"
      - "src/assets/js/directives/**/*.js"
      - "src/assets/js/controllers/dashboard.js"